import { ItemEntry } from "./types";

export const items: ItemEntry[] = [
  {
    name: "Almonds",
    icon: "🌰",
    nutrition: { calories: 577, protein: 21.3, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Apple",
    icon: "🍎",
    nutrition: { calories: 63, protein: 0.3, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Asparagus",
    nutrition: { calories: 20, protein: 2.2, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Wheat",
    icon: "🌾",
    nutrition: { calories: 367, protein: 10.9, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Banana",
    icon: "🍌",
    nutrition: { calories: 89, protein: 1.1, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Basella",
    icon: "🌿",
    nutrition: { calories: 19, protein: 1.8, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Beetroot",
    nutrition: { calories: 43, protein: 1.6, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Bittergourd",
    icon: "🥒",
    nutrition: { calories: 19, protein: 0.8, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Brocolli",
    icon: "🥦",
    nutrition: { calories: 34, protein: 2.7, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Brown Rice",
    icon: "🍚",
    nutrition: { calories: 362, protein: 8, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Butter",
    icon: "🧈",
    nutrition: { calories: 722, protein: 0.5, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Button Mushroom",
    icon: "🍄",
    nutrition: { calories: 22, protein: 3.1, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Capsicum",
    nutrition: { calories: 31, protein: 1, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Baby Carrot",
    icon: "🥕",
    nutrition: { calories: 35, protein: 0.6, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Cashew",
    icon: "🌰",
    nutrition: { calories: 553, protein: 18, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Chana Dal",
    nutrition: { calories: 374, protein: 22, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Chickpea",
    nutrition: { calories: 364, protein: 19, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Coconut Desiccated",
    icon: "🥥",
    nutrition: { calories: 684, protein: 5, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Cucumber",
    icon: "🥒",
    nutrition: { calories: 15, protein: 0.6, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Dried Black Fungus",
    icon: "🍄",
    nutrition: { calories: 285, protein: 6, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Dried Shiitake",
    icon: "🍄",
    nutrition: { calories: 293, protein: 6, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Egg",
    icon: "🥚",
    nutrition: { calories: 127, protein: 13, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Flax Seeds",
    nutrition: { calories: 534, protein: 18, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Garlic",
    icon: "🧄",
    nutrition: { calories: 150, protein: 6.6, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Ginger",
    nutrition: { calories: 80, protein: 1.8, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Green Beans",
    nutrition: { calories: 31, protein: 1.8, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "ID Batter",
    nutrition: { calories: 144.3, protein: 5.5, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Jalapeno",
    icon: "🌶️",
    nutrition: { calories: 20.3, protein: 0.6, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Kala Chana",
    nutrition: { calories: 350, protein: 19, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Maida",
    icon: "🌾",
    nutrition: { calories: 364, protein: 10, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Mango",
    icon: "🥭",
    nutrition: { calories: 60, protein: 0.8, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Mint",
    icon: "🍃",
    nutrition: { calories: 42, protein: 3.75, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Miso paste",
    nutrition: { calories: 199, protein: 12, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Moong Dal",
    nutrition: { calories: 360, protein: 22, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Onion",
    icon: "🧅",
    nutrition: { calories: 40, protein: 1.1, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Orange",
    icon: "🍊",
    nutrition: { calories: 47, protein: 0.9, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Peanuts",
    icon: "🥜",
    nutrition: { calories: 567, protein: 26, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Pearl Barley",
    icon: "🌾",
    nutrition: { calories: 352, protein: 10, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Potato",
    icon: "🥔",
    nutrition: { calories: 77, protein: 2, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Quinoa",
    icon: "🌾",
    nutrition: { calories: 371, protein: 16.3, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Radish",
    nutrition: { calories: 18, protein: 0.6, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Rajma",
    nutrition: { calories: 333, protein: 24, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Sabudana",
    icon: "🥔",
    nutrition: { calories: 332, protein: 0, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Semolina",
    icon: "🌾",
    nutrition: { calories: 360, protein: 13, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Shallots",
    icon: "🧅",
    nutrition: { calories: 72, protein: 2.5, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Spinach",
    icon: "🥬",
    nutrition: { calories: 23, protein: 2.9, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Sugar",
    icon: "🍭",
    nutrition: { calories: 387, protein: 0, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Sugarcane Juice",
    icon: "🧃",
    nutrition: { calories: 70, protein: 0, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Sweet Potato",
    icon: "🍠",
    nutrition: { calories: 86, protein: 1.6, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Tomato",
    icon: "🍅",
    nutrition: { calories: 18, protein: 0.9, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Urad Dal",
    nutrition: { calories: 341, protein: 25, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Watermelon",
    icon: "🍉",
    nutrition: { calories: 30, protein: 0.6, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "White Rice",
    icon: "🌾",
    nutrition: { calories: 360, protein: 7, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
  {
    name: "Zucchini",
    icon: "🥒",
    nutrition: { calories: 17, protein: 1.2, fat: 0, carbohydrates: 0 },
    weight: 100,
  },
];
